USE eenmaalandermaal
CREATE LOGIN applicatie WITH PASSWORD = '5_GXnMV&jN4J%QZY'; --DIT IS HET WACHTWOORD DAT GEBRUIKT GAAT WORDEN IN DE LOKALE PHP! 
CREATE USER applicatie;
ALTER ROLE db_datareader ADD MEMBER applicatie;
ALTER ROLE db_datawriter ADD MEMBER applicatie;
ALTER DATABASE [eenmaalandermaal] SET MULTI_USER;
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO